// <auto-generated />
using System;
using HR.ServerMonitoring.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.ServerMonitoring.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922042430_AddSensorThreshold")]
    partial class AddSensorThreshold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HR.ServerMonitoring.Api.Models.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GasLevel")
                        .HasColumnType("REAL");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SensorDataEntries");
                });

            modelBuilder.Entity("HR.ServerMonitoring.Api.Models.SensorThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GasLevelMax")
                        .HasColumnType("REAL");

                    b.Property<double>("GasLevelMin")
                        .HasColumnType("REAL");

                    b.Property<double>("HumidityMax")
                        .HasColumnType("REAL");

                    b.Property<double>("HumidityMin")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SensorThresholds");
                });
#pragma warning restore 612, 618
        }
    }
}
